// Microsoft 365 E3 -> E5 -> E7 coverage model (Cyber Defense Matrix: NIST CSF 2.0 x asset classes).
// Ratings are an opinionated discussion view, not a licensing statement.
export type Tier = 'E3' | 'E5' | 'E7';
export interface Cell { lv: [number, number, number]; tag: string[]; items: Record<Tier, string[]> }
export const TIERS: Tier[] = ['E3', 'E5', 'E7'];
export const FUNCS: [string, string][] = [
  ['Govern', 'policy & oversight'], ['Identify', 'inventory & posture'], ['Protect', 'prevent'],
  ['Detect', 'find threats'], ['Respond', 'contain & fix'], ['Recover', 'restore'],
];
export const ROWS: [string, string][] = [
  ['Users', 'human identities'], ['Devices', 'endpoints'], ['Apps & Email', 'SaaS, M365 workloads'],
  ['Networks', 'access paths'], ['Data', 'files, mail, chats'], ['AI Agents', 'non-human identities'],
];
const C = (lv: number[], tag: string[], e3: string[] = [], e5: string[] = [], e7: string[] = []): Cell =>
  ({ lv: lv as Cell['lv'], tag, items: { E3: e3, E5: e5, E7: e7 } });
export const DATA: Record<string, Cell[]> = {
  "Users": [
    C([1,1,2], ["CA policy engine","PAM + basic IGA","Full IGA"],
      ["Conditional Access policy engine (Entra ID P1)"],
      ["PAM: Privileged Identity Management", "Basic IGA: Access Reviews, Entitlement Management (Entra ID P2)"],
      ["Full IGA: Entra ID Governance with lifecycle workflows (Entra Suite)"]),
    C([1,2,2], ["Sign-in logs","Identity risk & posture","+ Identity proofing"],
      ["Sign-in logs, Secure Score identity recommendations"],
      ["Entra ID Protection risk detections", "Identity posture from Defender for Identity"],
      ["IDV: Verified ID Face Check (identity proofing)"]),
    C([2,2,2], ["MFA, CA","+ Risk-based CA, PIM","+ Continuous access eval"],
      ["SSO, MFA, passwordless, Conditional Access (Entra ID P1)"],
      ["Risk-based Conditional Access", "Just-in-time admin (PIM)"],
      ["Universal Continuous Access Evaluation (Entra Suite)"]),
    C([0,2,2], ["-","ITDR","ITDR"],
      [],
      ["ITDR: Defender for Identity + Entra ID Protection", "Insider Risk Management (user behavior)"]),
    C([1,2,2], ["Manual revoke / reset","Attack disruption","Attack disruption"],
      ["Manual: revoke sessions, reset passwords"],
      ["XDR automatic attack disruption (disables compromised users)", "Automated investigation & response", "Security Copilot agents"]),
    C([1,1,1], ["SSPR, restore users","+ Compromised-user fix","Account recovery"],
      ["Self-service password reset, restore deleted users"],
      ["Compromised-user remediation (Defender for Office 365 P2)"]),
  ],
  "Devices": [
    C([2,2,2], ["Compliance, baselines","+ EPM","Compliance, baselines, EPM"],
      ["UEM: Intune compliance policies, security baselines, Windows Autopatch"],
      ["EPM: Intune Endpoint Privilege Management"]),
    C([1,2,2], ["Inventory, DEX","RBVM + CTEM","RBVM + CTEM"],
      ["Intune and Defender device inventory", "DEX: Intune Advanced Analytics"],
      ["RBVM: Defender Vulnerability Management (core)", "CTEM: Microsoft Security Exposure Management"]),
    C([2,2,2], ["EPP/NGAV, ASR","+ PKI, app patching","EPP/NGAV, ASR, PKI"],
      ["EPP/NGAV: Defender for Endpoint P1, ASR rules, web content filtering", "BitLocker, Credential Guard, App Control"],
      ["Cloud PKI, Enterprise App Management (third-party patching)"]),
    C([1,2,2], ["AV alerts only","EDR","EDR"],
      ["Antivirus alerts (Defender for Endpoint P1)"],
      ["EDR: Defender for Endpoint P2", "Advanced Hunting (KQL), Threat Analytics"]),
    C([1,2,2], ["Manual actions, Remote Help","AIR, live response","AIR, live response"],
      ["Manual response actions (P1)", "Intune Remote Help"],
      ["Automated investigation & response, live response, device isolation", "XDR attack disruption"]),
    C([1,2,2], ["Wipe / reset","Automated remediation","Automated remediation"],
      ["Intune wipe / Autopilot reset, Windows quick machine recovery"],
      ["Automated remediation from AIR"]),
  ],
  "Apps & Email": [
    C([1,2,2], ["Shadow IT discovery","CASB + App Governance","CASB + App Governance"],
      ["Shadow IT discovery (Defender for Cloud Apps discovery)"],
      ["CASB policies (Defender for Cloud Apps)", "OAuth App Governance"]),
    C([1,2,2], ["App catalog","SSPM","SSPM"],
      ["Cloud Discovery app catalog"],
      ["SSPM: SaaS posture (Defender for Cloud Apps)", "Attack paths across SaaS (Exposure Management)"]),
    C([2,2,2], ["SEG + ICES","+ CASB sessions","SEG + ICES + CASB"],
      ["SEG: Exchange Online Protection", "ICES: Defender for Office 365 P1 (Safe Links, Safe Attachments, anti-phishing)", "SSO to SaaS apps"],
      ["CASB session controls"]),
    C([1,2,2], ["Email detections (P1)","Email + SaaS detection","Email + SaaS detection"],
      ["Defender for Office 365 P1 detections"],
      ["Defender for Office 365 P2", "Defender for Cloud Apps anomaly detection", "Unified XDR incidents"]),
    C([1,2,2], ["ZAP","Email AIR, SAT","Email AIR, SAT"],
      ["Zero-hour auto purge (ZAP)"],
      ["Threat Explorer, email AIR, Teams message quarantine", "SAT: Attack Simulation Training"]),
    C([1,1,1], ["Item recovery","Item recovery","Item recovery"],
      ["Recoverable Items, version history"],
      [],
      []),
  ],
  "Networks": [
    C([0,0,2], ["-","-","SSE policy"],
      [],
      [],
      ["SSE policy: Entra Internet Access + Private Access (Global Secure Access)"]),
    C([0,1,2], ["-","Network device discovery","Traffic visibility"],
      [],
      ["Network device discovery (Exposure Management)"],
      ["Global Secure Access traffic logs, private app discovery"]),
    C([1,1,2], ["Firewall, VPN","Firewall, VPN","ZTNA + SWG"],
      ["Windows Firewall, Always On VPN, network protection (Defender for Endpoint P1)"],
      [],
      ["ZTNA: Entra Private Access (VPN replacement)", "SWG: Entra Internet Access (incl. AI gateway)"]),
    C([0,1,2], ["-","EDR network signals","+ SWG threat filtering"],
      [],
      ["Network signals in EDR, lateral-movement detection (Defender for Identity)"],
      ["SWG threat-intelligence filtering"]),
    C([0,1,2], ["-","Device isolation","+ Central access block"],
      [],
      ["Device isolation (network containment)"],
      ["Central block of destinations and private app access"]),
    C([0,0,0], ["-","-","-"],
      [],
      [],
      []),
  ],
  "Data": [
    C([1,2,2], ["Retention, Compliance Mgr","Records, DSPM","+ SAM site lifecycle"],
      ["Retention policies, Compliance Manager (basic)"],
      ["Records Management, Compliance Manager (premium)", "DSPM: Data Security Posture Management"],
      ["SAM: site ownership, inactive-site, and attestation policies (via Copilot)"]),
    C([1,2,2], ["Sensitive info types","EDM, classifiers","+ SAM oversharing reports"],
      ["Sensitive information types, Content explorer"],
      ["Exact Data Match, trainable classifiers, Activity explorer"],
      ["SAM: data access governance (oversharing) reports"]),
    C([1,2,2], ["Manual labels, M365 DLP","Auto-labels, Endpoint DLP, HYOK","+ SAM RAC / RCD"],
      ["Manual sensitivity labels, DLP (Exchange, SharePoint, OneDrive), BYOK"],
      ["Auto-labeling, Endpoint & Teams DLP, Customer Key, Double Key Encryption, Information Barriers"],
      ["SAM: Restricted Access Control, Restricted Content Discovery"]),
    C([1,2,2], ["Audit Standard","Insider Risk, Comms Compliance","Insider Risk, Comms Compliance"],
      ["Audit Standard (180 days)"],
      ["Insider Risk Management, Adaptive Protection, Communication Compliance, Audit Premium"]),
    C([1,2,2], ["eDiscovery Standard","eDiscovery Premium","eDiscovery Premium"],
      ["eDiscovery Standard (search, hold)"],
      ["eDiscovery Premium (review, analytics), Insider Risk cases"]),
    C([1,1,1], ["Retention, not backup","Retention, not backup","Retention, not backup"],
      ["Retention and preservation hold, recycle bin"],
      [],
      []),
  ],
  "AI Agents": [
    C([1,1,2], ["Agent ID platform","Agent ID platform","Agent 365 registry + IGA"],
      ["NHI: Entra Agent ID platform (agent identities, blueprints) - all Entra tenants"],
      [],
      ["Agent 365: Agent Registry", "ID Governance for agents, access packages, sponsors"]),
    C([1,1,2], ["DSPM for AI (basic)","DSPM for AI","Agent map + AI-SPM"],
      ["DSPM for AI (basic: app info, activity export, auditing)"],
      ["DSPM for AI (prompt & response view)"],
      ["Agent map, agent risk signals", "AI-SPM for Foundry & Copilot Studio agents"]),
    C([0,1,2], ["-","DLP for Copilot","CA + DLP for agents"],
      [],
      ["DLP for Microsoft 365 Copilot interactions; Copilot honors sensitivity labels"],
      ["Conditional Access & ID Protection for agents", "Inline DLP for agent prompts", "Agents inherit labels"]),
    C([0,0,2], ["-","-","Agent threat detection"],
      [],
      [],
      ["Defender detection for agent compromise", "Insider Risk for agents"]),
    C([0,0,2], ["-","-","Block agent actions"],
      [],
      [],
      ["Block risky agent actions", "Investigate & hunt with agent logs"]),
    C([0,0,1], ["-","-","Retire agents"],
      [],
      [],
      ["Lifecycle: retire ownerless agents"]),
  ],
};

export const PLATFORM: Record<Tier, string[]> = {
  E3: ["Secure Score", "Copilot Chat upgrades", "Defender portal (P1 workloads)"],
  E5: ["XDR: Defender XDR", "CTEM: Exposure Management", "Security Copilot (400 SCU / 1,000 users / month)", "Threat intelligence (ex-MDTI Premium)", "ISOC (preview) / Sentinel data grant"],
  E7: ["Microsoft 365 Copilot", "Agent 365 control plane", "SharePoint Advanced Management", "Entra Suite (SSE + IGA + IDV)"],
};

export const GLOSSARY: [string, string, string, string, string][] = [["Identity", "MFA", "Multifactor Authentication", "A sign-in needs two or more proofs, such as a password and a phone or a security key.", "Entra ID P1 (E3)"], ["Identity", "SSO", "Single Sign-On", "One sign-in gives access to many apps.", "Entra ID P1 (E3)"], ["Identity", "CA", "Conditional Access", "The Zero Trust policy engine. It allows, blocks, or asks for MFA based on user, device, location, and risk.", "Entra ID P1 (E3); risk-based CA needs Entra ID P2 (E5)"], ["Identity", "CAE", "Continuous Access Evaluation", "Ends a session in near real time when risk or policy changes, not only when the token expires. Universal CAE also applies to network traffic.", "Universal CAE: Entra Suite (E7)"], ["Identity", "SSPR", "Self-Service Password Reset", "Users reset their own passwords with no help-desk call.", "Entra ID P1 (E3)"], ["Identity", "PAM", "Privileged Access Management", "Controls admin rights: just-in-time, time-limited, and approved elevation.", "Entra Privileged Identity Management (E5)"], ["Identity", "PIM", "Privileged Identity Management", "The Microsoft product for PAM in Entra.", "Entra ID P2 (E5)"], ["Identity", "IGA", "Identity Governance and Administration", "Controls who has access to what, why, and for how long: joiner-mover-leaver processes and access reviews.", "Basic: Entra ID P2 (E5). Full: Entra ID Governance (E7)"], ["Identity", "ITDR", "Identity Threat Detection and Response", "Detects and stops attacks on identity systems (Active Directory, Entra ID), such as password spray or golden-ticket attacks.", "Defender for Identity + Entra ID Protection (E5)"], ["Identity", "IDV", "Identity Verification", "Proves that a person is who they say they are, for example with a government ID and a live selfie.", "Entra Verified ID Face Check (E7)"], ["Identity", "NHI", "Non-Human Identity", "An identity for an app, a workload, or an AI agent, not a person.", "Entra Agent ID (all tenants); security controls need Agent 365 (E7)"], ["Endpoint", "UEM", "Unified Endpoint Management", "Manages and configures all device types from one tool (device and app management).", "Intune Plan 1 (E3)"], ["Endpoint", "DEX", "Digital Employee Experience", "Measures device health as the user feels it (boot time, app crashes, battery) so IT can fix problems before users open tickets.", "Intune Advanced Analytics (E3 from 2026)"], ["Endpoint", "EPM", "Endpoint Privilege Management", "Users work as standard users and get admin rights only for one approved task, not permanent local admin rights.", "Intune Endpoint Privilege Management (E5 from 2026)"], ["Endpoint", "PKI", "Public Key Infrastructure", "Issues and manages certificates, for example for Wi-Fi, VPN, and device authentication.", "Microsoft Cloud PKI (E5 from 2026)"], ["Endpoint", "EPP", "Endpoint Protection Platform", "Prevention on the device: antivirus, exploit protection, and attack surface reduction.", "Defender for Endpoint P1 (E3)"], ["Endpoint", "NGAV", "Next-Generation Antivirus", "Antivirus that uses behavior and cloud machine learning, not only signatures.", "Defender Antivirus (E3)"], ["Endpoint", "AV", "Antivirus", "Software that finds and removes malware.", "Defender Antivirus (E3)"], ["Endpoint", "ASR", "Attack Surface Reduction", "Rules that block risky behavior, for example Office macros that start other programs.", "Defender for Endpoint P1 (E3)"], ["Endpoint", "EDR", "Endpoint Detection and Response", "Records device activity, detects attacks, and lets analysts investigate and respond.", "Defender for Endpoint P2 (E5)"], ["Endpoint", "RBVM", "Risk-Based Vulnerability Management", "Ranks vulnerabilities by real risk (known exploits, exposure, asset value), not only by CVSS score.", "Defender Vulnerability Management (E5)"], ["Endpoint", "AIR", "Automated Investigation and Response", "Investigates alerts and fixes them automatically.", "Defender for Endpoint P2 and Defender for Office 365 P2 (E5)"], ["Endpoint", "KQL", "Kusto Query Language", "The query language for threat hunting in Defender and Sentinel.", "Advanced Hunting (E5)"], ["Email & SaaS", "SEG", "Secure Email Gateway", "Filters email before it arrives (the MX record points to it). Blocks spam and known malware.", "Exchange Online Protection (E3)"], ["Email & SaaS", "ICES", "Integrated Cloud Email Security", "Email security that is built into the cloud mailbox, not a separate gateway in front of it. It finds phishing, BEC, and bad links and files that pass the gateway, and can remove mail after delivery. Gartner term.", "Defender for Office 365 P1 (E3 from 2026); P2 adds investigation (E5)"], ["Email & SaaS", "BEC", "Business Email Compromise", "Fraud by email, for example a fake CEO who asks for a wire transfer.", "Defender for Office 365 anti-impersonation"], ["Email & SaaS", "ZAP", "Zero-hour Auto Purge", "Removes email from inboxes after delivery when the email is later found to be malicious.", "Exchange Online Protection and Defender for Office 365 (E3)"], ["Email & SaaS", "SAT", "Security Awareness Training", "Phishing simulations and short training for users.", "Attack Simulation Training (E5)"], ["Email & SaaS", "CASB", "Cloud Access Security Broker", "Shows and controls the use of cloud apps: discovery, policies, and session control.", "Defender for Cloud Apps (discovery in E3, full in E5)"], ["Email & SaaS", "SSPM", "SaaS Security Posture Management", "Finds security misconfigurations in SaaS apps.", "Defender for Cloud Apps (E5)"], ["Email & SaaS", "OAuth", "Open Authorization", "The protocol that lets apps get access to data on a user's behalf. Risky OAuth apps are an attack path.", "App Governance (E5)"], ["Network", "SSE", "Security Service Edge", "Network security delivered from the cloud: SWG + ZTNA + CASB.", "Entra Internet Access + Entra Private Access (E7)"], ["Network", "ZTNA", "Zero Trust Network Access", "Access to one private app at a time, based on identity and device. Replaces the VPN.", "Entra Private Access (E7)"], ["Network", "SWG", "Secure Web Gateway", "Filters internet traffic by web category, threat, and AI app.", "Entra Internet Access (E7)"], ["Network", "VPN", "Virtual Private Network", "A tunnel that connects a device to the corporate network.", "Windows Always On VPN (E3)"], ["Data", "DLP", "Data Loss Prevention", "Stops sensitive data from leaving through email, sharing, devices, or AI prompts.", "Purview DLP (M365 workloads in E3; endpoint and Teams in E5)"], ["Data", "DSPM", "Data Security Posture Management", "Shows where sensitive data is, who can get to it, and the risk. DSPM for AI adds AI prompts and responses.", "Purview DSPM (E5); DSPM for AI basic in E3"], ["Data", "EDM", "Exact Data Match", "Finds your real records (for example, a customer table) instead of only patterns.", "Purview (E5)"], ["Data", "BYOK", "Bring Your Own Key", "You supply the root encryption key.", "Azure Rights Management (E3)"], ["Data", "HYOK", "Hold Your Own Key", "You keep a key that Microsoft never sees.", "Double Key Encryption (E5)"], ["Data", "DKE", "Double Key Encryption", "Two keys protect the content: one held by Microsoft and one held by you.", "Purview (E5)"], ["Data", "DAG", "Data Access Governance", "Reports on oversharing: sharing links, 'everyone' access, and permissions.", "SharePoint Advanced Management (with Copilot or E7)"], ["Data", "SAM", "SharePoint Advanced Management", "Copilot-readiness tools that control oversharing and content sprawl in SharePoint and OneDrive.", "Included with Copilot licenses and E7"], ["Data", "RAC", "Restricted Access Control", "Limits a SharePoint site to a named security group.", "SharePoint Advanced Management"], ["Data", "RCD", "Restricted Content Discovery", "Hides a site from search and Copilot results.", "SharePoint Advanced Management"], ["SOC & AI", "XDR", "Extended Detection and Response", "One incident view and response across endpoint, identity, email, and cloud apps.", "Defender XDR (E5)"], ["SOC & AI", "CTEM", "Continuous Threat Exposure Management", "A Gartner program that continuously finds, ranks, and fixes exposures, including attack paths to critical assets.", "Microsoft Security Exposure Management (E5)"], ["SOC & AI", "SIEM", "Security Information and Event Management", "Collects logs from many sources and correlates them into alerts.", "Microsoft Sentinel; ISOC preview (E5/E7)"], ["SOC & AI", "ISOC", "Integrated Security Operations Center", "SIEM features inside the Defender portal, with no separate Sentinel deployment.", "Preview for E5/E7 from Sept 23, 2026"], ["SOC & AI", "MDTI", "Microsoft Defender Threat Intelligence", "Microsoft threat intelligence: actor profiles, indicators, and reports.", "Now 'Threat intelligence' in Defender, no extra cost (E5)"], ["SOC & AI", "IoC", "Indicator of Compromise", "Evidence of an attack, such as a bad IP address, domain, or file hash.", "Threat intelligence in Defender (E5)"], ["SOC & AI", "SCU", "Security Compute Unit", "The capacity unit for Security Copilot.", "400 SCUs per 1,000 users each month (E5/E7)"], ["SOC & AI", "AI-SPM", "AI Security Posture Management", "Finds misconfigurations and risk in AI apps and agents.", "Defender via Agent 365 (E7)"], ["SOC & AI", "CSF", "Cybersecurity Framework (NIST)", "Six functions: Govern, Identify, Protect, Detect, Respond, Recover. The columns of the matrix.", "Framework, not a product"], ["SOC & AI", "AI TRiSM", "AI Trust, Risk, and Security Management", "A Gartner category for governing and securing AI: model and agent inventory, data protection, runtime controls.", "Agent 365 + Purview DSPM for AI (E7)"], ["SOC & AI", "CTI", "Cyber Threat Intelligence", "Research about attackers, their tools, and campaigns.", "Threat Analytics (E5)"], ["SOC & AI", "TIP", "Threat Intelligence Platform", "A tool that collects, enriches, and searches threat intelligence (actors, IoCs).", "Threat intelligence in Defender, ex-MDTI Premium (E5)"], ["SOC & AI", "UEBA", "User and Entity Behavior Analytics", "Learns normal behavior for users and devices and flags unusual activity.", "Sentinel / ISOC workspace; Insider Risk Management for data (E5)"], ["Data", "DCAP", "Data-Centric Audit and Protection", "Protection that travels with the data: classification, labels, encryption, and audit.", "Purview Information Protection (manual in E3, automatic in E5)"], ["Data", "IRM", "Insider Risk Management", "Microsoft meaning: detects risky user activity with data, such as data theft by a leaving employee. Older industry meaning: Information Rights Management (encryption).", "Purview Insider Risk Management (E5)"], ["Endpoint", "PKIaaS", "Public Key Infrastructure as a Service", "A certificate authority that the vendor runs in the cloud, so you need no on-premises CA servers.", "Microsoft Cloud PKI (E5 from 2026)"], ["Productivity", "UCaaS", "Unified Communications as a Service", "Cloud telephony, meetings, and chat.", "Teams Phone + Audio Conferencing (E5)"]];
